version: '3.1'

volumes:
  pg_timeManager:

services:
  timeManager_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=timeManager_db
    volumes:
      - pg_timeManager:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"